name: JWebConsole Develop CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'develop'

env:
  JAVA_VERSION: '11'
  JAVA_DISTRO: 'adopt'

jobs:
  gradle_dev_build:
    name: Gradle Dev Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: develop

      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Running gradle task
        uses: gradle/actions/setup-gradle@v4

      - name: Code check and Sonar publish
        run: ./gradlew clean spotlessCheck sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}